authors:
  - Olblak <me@olblak.com>

url: "https://github.com/updatecli/policies/"
documentation: "https://github.com/updatecli/policies/tree/main/updatecli/policies/hugo/netlify/README.md"
source: "https://github.com/updatecli/policies/tree/main/updatecli/policies/hugo/netlify/"
version: 0.1.0
vendor: Updatecli Project

licenses:
  - "Apache-2.0 license"

description: |
  Automatically update the HUGO version used by Netlify.