pipelineid: npm
automerge: false
labels:
  - "chore"
  - "dependencies"

scm:
  enabled: false
  #user: updatecli-bot
  #email: updatecli-bot@example.com
  #owner: updatecli
  #repository: website
  ##token: "xxx"
  #username: "updatecli-bot"
  #branch: main

versionpattern: "*"
