name: "deps(cargo): bump all policies"

# pipelineid: cargo/autodiscovery
automerge: false
labels:
  - dependencies

scm:
  enabled: false
  # kind defines the SCM kind to use for this policy
  # Accepted values: github, gitea, bitbucket, gitlab, stash
  kind: github 
  ## env_token defines the environment variable to use to retrieve the token
  env_token: GITHUB_TOKEN
  user: updatecli-bot
  #email: updatecli-bot@updatecli.io
  #owner: updatecli
  #repository: "repository"
  #token: "xxx"
  username: "updatecli-bot"
  branch: main
  # commitusingapi: false
  ## githubsearch specific parameters
  # search: 'org:MyOrg'
  # limit: 5
  # branch: '^main$|^master$'

# spec:
groupby: all

