name: "deps(cargo): bump all policies"

# pipelineid: cargo/autodiscovery
automerge: false

scm:
  enabled: false
  user: updatecli-bot
  #email: updatecli-bot@updatecli.io
  #owner: updatecli
  #repository: "repository"
  #token: "xxx"
  username: "updatecli-bot"
  branch: main

# spec:
groupby: all

