name: "deps(ko): bump all dependencies"
#pipelineid: ko/autodiscovery
automerge: false

scm:
  enabled: false
  user: updatecli-bot
  #email: updatecli-bot@updatecli.io
  #owner: updatecli
  #repository: "repository"
  #token: "xxx"
  username: "updatecli-bot"
  branch: main

# spec:
groupby: all

