authors:
  - Olblak <me@olblak.com>

url: "https://github.com/updatecli/policies/"
documentation: "https://github.com/updatecli/policies/tree/main/updatecli/policies/nodejs/netlify/README.md"
source: "https://github.com/updatecli/policies/tree/main/updatecli/policies/nodejs/netlify/"
version: 0.5.0
vendor: Updatecli Project

licenses:
  - "Apache-2.0 license"

description: |
  Automatically update the NodeJS version used by Netlify.
